theme: jekyll-theme-minimal
title: My projects' portfolio
author:
  name: Diana Arosemena
  email: diana.arosemena@gmail.com
description: Portfolio of projects made by Diana Arosemena, an Industrial Mechanical Engineer passionate about leveraging technology to solve complex problems and enhance operational efficiency.
