theme: jekyll-theme-minimal
title: My portfolio's homepage
author:
  name:  Diana Arosemena
  email: diana.arosemena@gmail.com
author:
  picture:  72526431.jpg
description: Portfolio of projects made by Diana Arosemena, an Industrial Mechanical Engineer passionate about leveraging technology to solve complex problems and enhance operational efficiency..
