theme: minima
plugins:
  - jekyll-feed
title: My projects' portfolio
author:
  name: Diana Arosemena
  email: diana.arosemena@gmail.com
  avatar: /assets/images/avatar.jpg
description: Portfolio of projects made by Diana Arosemena, an Industrial Mechanical Engineer passionate about leveraging technology to solve complex problems and enhance operational efficiency.
