theme: jekyll-theme-minimal
title: My portfolio's homepage

description: Portfolio of projects made by Diana Arosemena, an Industrial Mechanical Engineer passionate about leveraging technology to solve complex problems and enhance operational efficiency..
