theme: jekyll-theme-minimal
title: My portfolio's homepage
![72526431](https://github.com/d-arosemena/portfolio/assets/72526431/53b42f36-2b4f-45d3-867f-7b2582c67b9c)
description: Portfolio of projects made by Diana Arosemena, an Industrial Mechanical Engineer passionate about leveraging technology to solve complex problems and enhance operational efficiency..
